### PR TITLE
SPI-Bus selectable in constructor

### PR DESCRIPTION
**Pull request by bitconnector**
Hi
I was using this library on an ESP32. Because of My setup I had to use the second SPI-Bus for the CAN transceiver. Now I have written a Constructor which can be used to pass the SPI-device the MCP is connected to
I hope, this can be useful for others. Tell me If I should provide an example
Best regards
bitconnector

### CODE REVIEW

**Review by coryjfowler — APPROVED** [review]
Merging!

**Comment by justinschoeman** [comment]
This pull breaks use of the old API (without passing in an SPI object)
SPI = SPI;
In the constructor is fubar.  To fix, I renamed SPI to pSPI and changed the above to:
pSPI = &SPI;

**Comment by bitconnector** [comment]
I didn't thought of that. The Compiler can get confused because SPI is both the default SPI Object and simultaniously used as Pointer to the actual used SPI device

The fix suggested by renaming the SPI pointer inside the library should work. You just have to rename all instances of the SPI pointer inside of this library

I could create a second pull request if I should fix this @justinschoeman

**Comment by coryjfowler** [comment]
Well, that would certainly explain some issues I had when I went to use it some time back.  I made the changes to correct it.

But I don't think those changes worked.  Nevermind.

**Comment by justinschoeman** [comment]
I stashed my fix and pulled from master.  Seems to work fine now.

Thanks for fixing this.

**Comment by coryjfowler** [comment]
Thanks for checking it out.

**Comment by zalexzperez** [comment]
Hi,

But, how does one specify the SPI port during initialization with these changes? And how to set the pins?

I'm using an ESP32-S3 to drive an SPI display using the TFT_eSPI library. 
However, as soon as the MCP2515 is initialized, the display stops working.

So I figured both devices can't operate at the same time on the same SPI port. 

I want to use the faster FSPI peripheral for the display, running at 60-80MHz, and the slower SPI (SPI3) for CAN.

Thanks very much.

**Comment by coryjfowler** [comment]
Via argument overloading:
```
MCP_CAN CAN0(2);                              // CAN0 interface on default
SPI peripheral with pin 2 as chip select
MCP_CAN CAN1(SPI3, 6);                    // CAN1 interface on SPI3
peripheral with pin 6 as chip select
```

**Comment by zalexzperez** [comment]
> Via argument overloading: ``` MCP_CAN CAN0(2); // CAN0 interface on default SPI peripheral with pin 2 as chip select MCP_CAN CAN1(SPI3, 6); // CAN1 interface on SPI3 peripheral with pin 6 as chip select ```


So you'd first create the spi3 object like this:
SPIClass SPI3(HSPI);

and then pass its address as an argument:
MCP_CAN CAN0(&SPI3, 6);

Right? 

Figuring out what constant to use (HSPI vs VSPI) was a little confusing, as HSPI used to be the fastest SPI on the 1st gen ESP32.

Thanks for your help.

**Pull request merged**
