### PR TITLE
Improved sleep functionality

### PR DESCRIPTION
**Pull request by ZakKemble**
Hey Cory, thanks for maintaining this library!

Entering and exiting sleep mode is kinda wack compared with other modes. Need to spam the mode request and read from the CAN STATUS register until the mode change is complete.

Manually exiting sleep mode requires turning on the wake interrupt and setting the wake interrupt flag. This trick was found at https://github.com/mkleemann/can/blob/master/can_sleep_mcp2515.c

Also used the F() macro to keep the debugging strings in flash.

### CODE REVIEW

**Comment by silardg** [comment]
Put this code into the lib and eventually in the original! It works like a charm. I have been searching for a solution, and I have found it here. Awesome work @zkemble

**Comment by coryjfowler** [comment]
I have not had time to test zkemble's work myself and after silardg's comment, merged and done.

**Comment by 1e1** [comment]
Hi @coryjfowler 
Could you accept the merge request?

**Comment by Saimon574** [comment]
Come si fa ad accettare la richiesta? Inviato dal mio telefono Huawei

**Comment by 1e1** [comment]
@Saimon574 The Maintainer only can merge the PR
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

**Comment by coryjfowler** [comment]
I do not know why i did not do what I said I would two years ago.  Apologies all!

**Pull request merged**
